### ISSUE TITLE
example_vbwkde.cfg unable to be run through pipeline.py

### ISSUE THREAD

**Issue by steven-j-wren** [icecube/pisa#361]
When I try to run `pipeline.py` with the `example_vbwkde.cfg` I get the following error:

```
Stevens-MacBook-Pro-2:pisa steven$ python pisa/core/pipeline.py --pipeline pisa/resources/settings/pipeline/example_vbwkde.cfg --outdir OUTPUT/ProfileScans/MPHYS/ --png -v
PISA running in double precision (FP64) mode.

[ WARNING] Directory "OUTPUT/ProfileScans/MPHYS/" already exists
[   ERROR] Error occurred computing outputs in stage reco / service vbwkde ...
Traceback (most recent call last):
  File "pisa/core/pipeline.py", line 686, in <module>
    pipeline, outputs = main(return_outputs=True) # pylint: disable=invalid-name
  File "pisa/core/pipeline.py", line 598, in main
    outputs = pipeline.get_outputs(idx=stop_idx)
  File "/Users/steven/IceCube/PISA/pisa/pisa/utils/profiler.py", line 92, in profiled_func
    return func(*args, **kwargs)
  File "pisa/core/pipeline.py", line 261, in get_outputs
    outputs = stage.get_outputs(inputs=inputs)
  File "/Users/steven/IceCube/PISA/pisa/pisa/utils/profiler.py", line 92, in profiled_func
    return func(*args, **kwargs)
  File "/Users/steven/IceCube/PISA/pisa/pisa/core/stage.py", line 571, in get_outputs
    nominal_transforms_hash=nominal_transforms_hash
  File "/Users/steven/IceCube/PISA/pisa/pisa/utils/profiler.py", line 92, in profiled_func
    return func(*args, **kwargs)
  File "/Users/steven/IceCube/PISA/pisa/pisa/core/stage.py", line 470, in get_transforms
    transforms = self._compute_transforms()
  File "/Users/steven/IceCube/PISA/pisa/pisa/stages/reco/vbwkde.py", line 977, in _compute_transforms
    self.characterize_resolutions()
  File "/Users/steven/IceCube/PISA/pisa/pisa/stages/reco/vbwkde.py", line 1238, in characterize_resolutions
    feature, weights=weights, **vbwkde_kwargs
  File "/Users/steven/IceCube/PISA/pisa/pisa/utils/vbwkde.py", line 282, in vbwkde
    evaluate_dens=True, evaluate_at=None
  File "/Users/steven/IceCube/PISA/pisa/pisa/utils/vbwkde.py", line 163, in fbwkde
    min_bandwidth=min_bandwidth
  File "/Users/steven/IceCube/PISA/pisa/pisa/utils/vbwkde.py", line 410, in isj_bandwidth
    disp=True
  File "/Users/steven/.virtualenv/standard/lib/python2.7/site-packages/scipy/optimize/zeros.py", line 438, in brentq
    r = _zeros._brentq(f,a,b,xtol,rtol,maxiter,args,full_output,disp)
  File "/Users/steven/IceCube/PISA/pisa/pisa/utils/vbwkde.py", line 538, in fixed_point_numba_loops
    k0 = _K0[s]
IndexError: index 6 is out of bounds for axis 0 with size 5
```

Seems to me to be not so much an error with that particular `cfg` as it is with the vbwkde itself.

**Comment by LeanderFischer** [comment]
closing since it didn't seem to bother anyone for years now..
