### ISSUE TITLE
example_vbwkde.cfg needs file with more events

### ISSUE THREAD

**Issue by jllanfranchi** [icecube/pisa#455]
Tried orders of magnitude; only runs fully with 1e4 events or more. The 1e2 toy events file in pisa_examples now doesn't have enough events for that one to run to completion. Replacing it would mean we need to store a 9.5 MiB file (once fluxes are attached) vs. the 425 KiB file that's there now.

Command:
```bash
pisa-pipeline -p settings/pipeline/example_vbwkde.cfg --outdir /tmp/delme -v
```
Error message given for file with too-few events:
```
Traceback (most recent call last):
  File "/home/justin/anaconda2/bin/pisa-pipeline", line 9, in <module>
    load_entry_point('pisa', 'console_scripts', 'pisa-pipeline')()
  File "/home/justin/src/pisa/pisa/core/pipeline.py", line 660, in main
    outputs = pipeline.get_outputs(idx=stop_idx) # pylint: disable=redefined-outer-name
  File "/home/justin/src/pisa/pisa/utils/profiler.py", line 125, in profiled_func
    return func(*args, **kwargs)
  File "/home/justin/src/pisa/pisa/core/pipeline.py", line 323, in get_outputs
    outputs = stage.run(inputs=inputs) # pylint: disable=redefined-outer-name
  File "/home/justin/src/pisa/pisa/core/stage.py", line 440, in run
    return self.get_outputs(inputs=inputs)
  File "/home/justin/src/pisa/pisa/utils/profiler.py", line 125, in profiled_func
    return func(*args, **kwargs)
  File "/home/justin/src/pisa/pisa/core/stage.py", line 503, in get_outputs
    nominal_transforms_hash=nominal_transforms_hash
  File "/home/justin/src/pisa/pisa/utils/profiler.py", line 125, in profiled_func
    return func(*args, **kwargs)
  File "/home/justin/src/pisa/pisa/core/stage.py", line 398, in get_transforms
    transforms = self._compute_transforms()
  File "/home/justin/src/pisa/pisa/stages/reco/vbwkde.py", line 1003, in _compute_transforms
    self.characterize_resolutions()
  File "/home/justin/src/pisa/pisa/stages/reco/vbwkde.py", line 1146, in characterize_resolutions
    tgt_max_binwidth_factor=self.tgt_max_binwidth_factors[char_dim]
ValueError: No events were found! Do you apply a cut that removes all relevant events? E.g. this can occur if you cut away downgoing events but then define true-coszen bins in the downgoing region.
```

**Comment by LeanderFischer** [comment]
`example_vbwkde.cfg` simply doesn't exist anymore
